name: fintamer
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.34
  shake: ^3.0.0
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.27.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock_data/
    - assets/icons/
    - .env